# Generated by Django 2.0.5 on 2018-06-19 15:03

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=2000)),
                ('status', models.CharField(choices=[('Draft', 'Not Published Yet'), ('Published', 'Published'), ('Done', 'Concept achieved the goal with success'), ('Closed', 'Concept closed without success')], default='Draft', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(verbose_name='Publication date')),
                ('category', models.CharField(blank=True, choices=[('Art', 'Art'), ('Fashion', 'Fashion')], max_length=50)),
                ('goal', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(0)])),
                ('pledge', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(0)])),
                ('backers_counter', models.IntegerField(default=0)),
                ('days_to_go', models.IntegerField(choices=[(30, '30 days to go, platform fee is 5% of the project cost'), (45, '45 days to go, platform fee is 10% of the project cost'), (60, '60 days to go, platform fee is 15% of the project cost')], default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tags')),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='concepts_storage_app.Keywords', verbose_name='Tags'),
        ),
    ]
