# Generated by Django 2.0.3 on 2018-04-19 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('goal', models.IntegerField(default=0)),
                ('pledge', models.IntegerField(default=0)),
                ('backers_counter', models.IntegerField(default=0)),
                ('day_to_go', models.CharField(choices=[('30', '30 days to go, platform fee is 5% of the project cost'), ('45', '45 days to go, platform fee is 10% of the project cost'), ('60', '60 days to go, platform fee is 15% of the project cost')], default='30', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
