# Generated by Django 2.0.3 on 2018-04-17 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('concepts_storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 20, 3, 8, 767140, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
