# Generated by Django 2.0.3 on 2018-04-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts_storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Comics', 'Comics'), ('Crafts', 'Crafts'), ('Dance', 'Dance'), ('Design', 'Design'), ('Fashion', 'Fashion'), ('Film & Video', 'Film & Video'), ('Food', 'Food'), ('Games', 'Games'), ('Journalism', 'Journalism'), ('Music', 'Music'), ('Photography', 'Photography'), ('Publishing', 'Publishing'), ('Technology', 'Technology'), ('Theater', 'Theater')], default='Art', max_length=30),
        ),
    ]
